# 連立１次方程式

In [64]:
using BenchmarkTools

In [39]:
A = [1 2 ; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [46]:
b = [2,3]

2-element Array{Int64,1}:
 2
 3

In [54]:
c = A \ b

2-element Array{Float64,1}:
 -1.0
  1.5

In [56]:
A * c

2-element Array{Float64,1}:
 2.0
 3.0

In [49]:
A'

2×2 Array{Int64,2}:
 1  3
 2  4

In [51]:
E = eye(2)

2×2 Array{Float64,2}:
 1.0  0.0
 0.0  1.0

In [57]:
E \ c

2-element Array{Float64,1}:
 -1.0
  1.5

In [4]:
for i in 1:3
    E =  eye(i)
    println(E)
end


[1.0]
[1.0 0.0; 0.0 1.0]
[1.0 0.0 0.0; 0.0 1.0 0.0; 0.0 0.0 1.0]


In [50]:
r = 3.0
A = [(i==j-1) for i in 1.0:3.0, j in 1.0:3.0]
A[end]=0
A

3×3 Array{Bool,2}:
 false   true  false
 false  false   true
 false  false  false

In [77]:
function iniArray()
    n = 100
    A = zeros(Float64,(n,n))
    for i in 1:n, j in 1:n
        if i==j
            A[i,j] = 2 
        elseif i==j-1
            A[i,j] = 3
        elseif i==j+1
            A[i,j] = 4
        end
    end
end
a = @benchmark iniArray()

BenchmarkTools.Trial: 
  memory estimate:  78.20 KiB
  allocs estimate:  2
  --------------
  minimum time:     24.636 μs (0.00% GC)
  median time:      31.659 μs (0.00% GC)
  mean time:        48.271 μs (20.46% GC)
  maximum time:     5.086 ms (83.02% GC)
  --------------
  samples:          10000
  evals/sample:     1

In [101]:
function CalcArray(n)
    A = zeros(Float64,(n,n))
    b = zeros(Float64, n)
    b[end] = 1
    
    for i in 1:n    
        if i+1<=n
            A[i,i+1] = 2
        end
        
        A[i,i] = 3        
        
        if i-1>0
            A[i,i-1] = 4
        end
    end

    A[1,1] = 10
    A[1,2] = 1
    A[end,1:end-1] = 0
    A[end,end] = 1

    return A
    end
# @benchmark 
@time CalcArray(10)

  0.135647 seconds (4.46 k allocations: 219.881 KiB)


10×10 Array{Float64,2}:
 10.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
  4.0  3.0  2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
  0.0  4.0  3.0  2.0  0.0  0.0  0.0  0.0  0.0  0.0
  0.0  0.0  4.0  3.0  2.0  0.0  0.0  0.0  0.0  0.0
  0.0  0.0  0.0  4.0  3.0  2.0  0.0  0.0  0.0  0.0
  0.0  0.0  0.0  0.0  4.0  3.0  2.0  0.0  0.0  0.0
  0.0  0.0  0.0  0.0  0.0  4.0  3.0  2.0  0.0  0.0
  0.0  0.0  0.0  0.0  0.0  0.0  4.0  3.0  2.0  0.0
  0.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0  3.0  2.0
  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

In [108]:
dv = [1;2;3;4]
ev = [7;8;9]
ST = SymTridiagonal(dv,ev)

4×4 SymTridiagonal{Int64}:
 1  7  ⋅  ⋅
 7  2  8  ⋅
 ⋅  8  3  9
 ⋅  ⋅  9  4

In [116]:
x = [1,2,3,4]
norm(x[2:4],1)

9.0

In [3]:
F = [1 2 3;4 5 6;7 8 9]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [132]:
i = [1;1;1]

3-element Array{Int64,1}:
 1
 1
 1

In [139]:
G=F'*i


3-element Array{Int64,1}:
 12
 15
 18

In [4]:
UpperTriangular(F)

3×3 UpperTriangular{Int64,Array{Int64,2}}:
 1  2  3
 ⋅  5  6
 ⋅  ⋅  9

In [13]:
C = fill(1,(5,5))
C = UpperTriangular(C)-eye(C)

5×5 Array{Int64,2}:
 0  1  1  1  1
 0  0  1  1  1
 0  0  0  1  1
 0  0  0  0  1
 0  0  0  0  0